# Change these first
owner: adlaidyson-ffp # Your GitHub organization or username, where this repository lives
repo: statusadffp # The name of this repository
user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"

sites:
  - name: Main Website
    url: https://www.fusedframe.co.uk
  - name: Link in Bio
    url: https://links.adlaidyson.co.uk
  - name: Client Galleries (PICR)
    url: https://clients.adlaidyson.co.uk
  - name: ADFFP Cloud (NextCloud)
    url: https://cloud.fusedframe.co.uk

status-website:
  cname: status.adffp.uk
  logoUrl: https://cdn-eu.fusedframe.co.uk/main-logos/jpg/squarefavicon-nocircle.jpg
  name: Service Statuses
  introTitle: "**Srvice Statuses**"
  introMessage: View the status for all services used or hosted by Adlai Dyson | Fused Frame Photography.
  navbar:
    - title: Status
      href: /
    - title: Main Website
      href: https://www.fusedframe.co.uk
    - title: All Links
      href: https://links.adlaidyson.co.uk
