owner: adlaidyson-ffp
repo: statusadffp

sites:
  - name: Main Website and Galleries
    url: https://www.fusedframe.co.uk
  - name: EXIF Overlay: Clean Summaries for Every Shot!
    url: https://exifoverlay.com
  - name: Link in Bio
    url: https://links.adlaidyson.co.uk
  - name: ADFFP Cloud (NextCloud)
    url: https://cloud.fusedframe.co.uk
  - name: DocuSign (Document Signing Platform)
    url: https://sign.adlaidyson.co.uk
  - name: Content Delivery Network (CDN) – Cloudflare R2
    url: https://cdn-eu.fusedframe.co.uk/main-branding/status.html
  - name: URL Shortener – adffp.uk
    url: https://adffp.uk
  - name: Shutter Society Mastodon
    url: https://shuttersociety.uk
  - name: Upper Haugh Weather (Frontend)
    url: https://upperhaughweather.uk
  - name: Upper Haugh Weather (API Backend)
    url: https://api.upperhaughweather.uk/weather
  - name: VaultWarden Password Manager
    url: https://vault.adlaidyson.co.uk
  - name: QR Code Generator
    url: https://qr.adlaidyson.co.uk
  - name: Authentik SSO
    url: https://sso.adlaidyson.co.uk

status-website:
  links:
    - rel: stylesheet
      href: https://cdn-eu.fusedframe.co.uk/stylesheets/upptime.css
  cname: status.adffp.uk
  logoUrl: https://cdn-eu.fusedframe.co.uk/main-logos/jpg/squarefavicon-nocircle.jpg
  name: Service Statuses
  introTitle: "**Service Statuses**"
  introMessage: View the status for all services used or hosted by Adlai Dyson | Fused Frame Photography.
  navbar:
    - title: Status
      href: /
    - title: Main Website
      href: https://www.fusedframe.co.uk
    - title: All Links
      href: https://links.adlaidyson.co.uk

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
